### ISSUE TITLE
Reveiw 

### ISSUE THREAD

**Issue by aman-coder** [aman-coder/Realstate#1]
# please Review

**Comment by aman-coder** [comment]
- review it and provide Appropriate Changes if Required

**Comment by AdityaMittal9123** [comment]
**# Some changes that should be done**

1. The images in properties section should be styled as previously (i.e., in left column that should be a single picture of 
height 100% and in right there should be three .) #Note take an idea  from  the wireframe .
2. the height of about us and the topmost section should also be 100vh . 
3. the card content in the "client feedback" section should be well styled . (take an idea from wireframe)

**Comment by aman-coder** [comment]
- Okay, I will fix them.
